version: '2.1'
services:
  api-gateway:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      COURSES_URL: '192.168.99.101'
      COURSES_PORT: '3000'
      COURSES_ENTRY: 'courses-ms/resources/courses'
      PAYMENTS_URL: ''
      PAYMENTS_PORT: ''
      PAYMENTS_ENTRY: ''
      PRODUCTS_URL: '192.168.99.101'
      PRODUCTS_PORT: '3000'
      PRODUCTS_ENTRY: 'products'
      STORES_URL: ''
      STORES_PORT: ''
      STORES_ENTRY: ''
      USERS_URL: ''
      USERS_PORT: ''
      USERS_ENTRY: ''
    ports:
      - '5000:5000'